### ISSUE TITLE
Allow explicitly enabling/disabling compilation of optional components

### ISSUE THREAD

**Issue by simonvanderveldt** [linuxaudio/new-session-manager#16]
Good job on moving this forward! :+1: 

Quick question: Can the compilation of the optional components which are currently behindt an automagic FLTK check be made explicit?

P.S. I noticed fluid is mentioned in the dependencies as well, I don't know what that is though, which package/application does that belong to?

**Comment by falkTX** [comment]
fluid is the fltk ui designer.
On Debian the package name that contains is called fluid. Others might have it as part of fltk.

**Comment by diovudau** [comment]
They are optional from a technical standpoint only. They belong to the project. Especially nsm-proxy is needed. I suggest we make them non-optional completely.

**Comment by simonvanderveldt** [comment]
> They are optional from a technical standpoint only. They belong to the project. Especially nsm-proxy is needed. I suggest we make them non-optional completely.

That would work for me/us as well of course.
Would that not be problematic for people wanting to use it on a headless setup? Not sure if that's a supported use case?

**Comment by diovudau** [comment]
I see. Headless without any FLTK, or even X11, dependencies installed. That is a realistic usecase.
Then: Installed by default with the option to disable. I guess that is what you meant initially?

**Comment by simonvanderveldt** [comment]
> Then: Installed by default with the option to disable. I guess that is what you meant initially?

I'm not sure that's the same, it might be depending on what you mean exactly :) 
But basically the goals is to have a deterministic build, which means no automagic dependencies.

If an optional feature requires a library that feature should be explicitly enabled. This means the build will fail if this feature is enabled and the library is not installed and the build will of course work when the library is installed. It also means one can disable a feature even though the library is installed.

It can be behind a functional flag (something like enable-nsm-proxy) or a technical flag (something like enable-fltk). Functional is generally more clear but that's of course up to the project/you to decide :)

**Comment by diovudau** [comment]
new-session-manager and nsm-proxy should be build and installed by default, not having the right FLTK dependencies will be an error.  There will be an opt-out for the GUI tools, making it possible to only build nsmd and jackpatch.

We need a point release soon for Ubuntu packaging, this will be included (I hope).

**Comment by diovudau** [comment]
Solved. Thanks simonvanderveldt

**Comment by simonvanderveldt** [comment]
Fixed in 326a46ce9f5c9abe730da55a7f6f339578b41ae8
