### ISSUE TITLE
Ability to delete sessions?

### ISSUE THREAD

**Issue by mxmilkiib** [linuxaudio/new-session-manager#17]
Apparently this wasn't in the original nsm to avoid all moral hazard the UI might have toward a situation where a user accidentally deletes a project they really didn't want to. 

But I keep clicking New when I really want to click Add Client to Session.

Maybe deleting could have a check like GitHub? And/or use a custom trash dir or `~/.local/share/Trash`?

**Comment by diovudau** [comment]
Implemented in Argodejo.

**Comment by diovudau** [comment]
In general (which addresses missclicking as well): The old GUI is really there for completeness sake. It is not very well designed and practically untested with real users. That was supposedly a "works for me" project.  This fork is to develop the daemon and maybe add a little fix here and there to jackpatch and nsm-proxy. The FLTK GUI will be kept around and functional, but no other improvements will happen, it is a lost cause. Instead, as the README suggest, Argodejo is my focus of attention.

**Comment by diovudau** [comment]
Addendum: the above is still true, I personally do not want to spend my time on the legacy-gui. However, @falkTX  has given the legacy-gui some attention already, which I still welcome. Current git already has some of the changes. See commit logs and CHANGELOG for now.

**Comment by falkTX** [comment]
also something else worth noting in regards to deletion: when a client is removed from the project, its project file remains in the session folder. so the session folder can very easily become cluttered with trash if one tries a lot of stuff.

even worse, if files are there from a previous time a session was chosen, and by random chance the same client name and id match what was a previously used... it means the client will load the old project that was supposed to not be there anymore

if we ever want to fix this.. it would be quite tricky, technically speaking.
only the client knows exactly how to properly delete its project, and the original spec does not cover this situation.
