### ISSUE TITLE
Font is not visible

### ISSUE THREAD

**Issue by mxmilkiib** [linuxaudio/new-session-manager#20]
I'm not sure what has happened here, I don't think I have changed anything myself since the last time I used it and it worked;

![image](https://user-images.githubusercontent.com/108225/85297251-6d4dcd00-b49a-11ea-8df6-5bb7a4d67449.png)

**Comment by grammoboy2** [comment]
As a user the situation is pretty simple I think. You've a choice between two GUIs for NSM. 

If you want to use the original GUI, you will likely want to download it from the original source instead, cause you're better off with the NTK version most likely, which is easy to build anyway:

https://github.com/original-male/non

If you want to use Argodejo as GUI, you can download that instead.

Same is true for https://github.com/linuxaudio/new-session-manager/issues/18 I guess.

**Comment by falkTX** [comment]
That is irrelevant for the ticket here. And whichever one is easier to build is debatable, you cannot even follow the readme instructions as-is anyway. https://github.com/original-male/non/issues/286

**Comment by mxmilkiib** [comment]
I think I posted the console log in IRC before, but here it is again;
```
> nsm-legacy-gui
[nsm-legacy-gui] ../src/Endpoint.cpp:205 init(): Creating OSC server
[nsm-legacy-gui] ../src/legacy-gui.cpp:1396 main(): Starting daemon...
[nsm-legacy-gui] ../src/Endpoint.cpp:1159 osc_thread(): OSC Thread running
X_ChangeProperty: BadValue (integer parameter out of range for operation) 0x0
[nsmd] ../src/nsmd.cpp:2262 main(): Going to connect to GUI at: osc.udp://rose.local:19080/
[nsmd] ../src/nsmd.cpp:2285 main(): Session root is: /home/milk/NSM Sessions
[nsmd] ../src/Endpoint.cpp:205 init(): Creating OSC server
NSM_URL=osc.udp://rose.local:10096/
[nsmd] ../src/nsmd.cpp:2160 announce_gui(): Registered with GUI
[nsmd] ../src/nsmd.cpp:1580 osc_list(): Listing sessions
X_ChangeGC: BadFont (invalid Font parameter) 0x0
X_ChangeGC: BadFont (invalid Font parameter) 0x0
```

**Comment by mxmilkiib** [comment]
I can see the font now, happy day, no idea what changed, maybe Harfbuzz :)
