### ISSUE TITLE
Legacy-GUI: Attaching to a running nsmd server does not show icons

### ISSUE THREAD

**Issue by diovudau** [linuxaudio/new-session-manager#41]
This is not a regression. I have tested this with Non-Session-Manager v1.2  Arch release package and the bug is the same.

If a session inside nsmd is already running (with clients) and you connect the GUI to it it will not show the program Icon.
Some programs have their icons visible, some don't

For copy and paste convenience I will use a fixed OSC port here, but this was tested without. 

**Steps to reproduce:**

in terminal 1:
`nsmd --osc-port=12345`

in terminal 2:
`non-session-manager --nsm-url=osc.udp://0.0.0.0:12345/`
Create a new session "test". Add one client (e.g. Patroneo) to session
Confirm that you see the icon
Quit the GUI via window manager or QUIT button. This will not quit the server but just detach.

Execute again, to attach to a running session:
`non-session-manager --nsm-url=osc.udp://0.0.0.0:12345/`
Icon is gone.
If you stop and resume Patroneo the icon will still be missing.

**Comment by diovudau** [comment]
The missing optional-gui button was an nsmd issue and is now fixed in git. I edited it out of the original issue.

**Comment by diovudau** [comment]
I fixed the the label="()" problem and edited it out from the original issue. Only the icon remains.

**Comment by brummer10** [comment]
When you add the issue number to the commit message, example " Detach label storing from the presense of a GUI. Send label with client list when a gui announces to already running session, issue #41" it will be easier to follow.

**Comment by diovudau** [comment]
By coincidence I have stumbled upon the reason of this problem. It is unfixable in legacy-gui, or any GUI for that matter.

Background info:

Icon lookup is done by client name, which is NOT the executable name but whatever the client reports. For some clients this is the same and it will always find an icon, but by pure luck of similar naming. This is also case-sensitive!

For so called "dumb clients", programs that are not nsm-capable (that never send the "announce" message), basename(executable) is always the client name.

However, when nsmd adds a client itself it is first registered as "dumb client" no matter what and only after the client announced itself upgraded to a real nsm client, which changes the internal name to the self-reported name from the clients announce message. This "dumb client"-state is sent to the GUI as well, at which point it looks up the icon by the executable name. It keeps the icon after the client-upgrade.

When attaching the GUI to a running daemon all clients are upgraded, the name is already self-reported. The GUI does not know the executable names and cannot find the icons.
The same happens when a program from outside knows the NSM_URL environment variable and announces itself. It will be registered with its self-reported name directly.  There are one or two more scenarios in nsmd.cpp where clients are created and the client/new message is sent.

Note: The executable name is also send in the announce message, so we always have that.

**Proposed solutions, in order of likeliness:**

1. Mirror the most common behaviour: Send two client/new message for each client, no matter how it arrived in the session. The first is always with the executable, the second may be the self reported name (or it may be the executable again, for dumb clients). Actually for dumb clients it can stay at one message.  It needs testing of course, but I anticipate that this will need no changes in GUIs, clients etc.  Only the server needs a few lines more to send more messages.

1. Don't change the server behaviour but change legacy-gui (and Argodejo) to work around that problem, do some guess-work by ignoring case-sensitivity, do reverse-lookup through in the system themselves, fuzzy regex matching.  This leaves the server unchanged, but still doesn't guarantee a success. However, it is still a 80/20 solution, which is a good quota for a cosmetic problem such as icons.

1. Create a new message that explicitly reports the executable name. GUIs need to react to that. This can have unknown behaviour in the programs we don't know about. This is at least a MINOR API change. If it turns out that not all programs deal with message that were not expected this is a MAJOR API change, which would be ridiculous for such a thing. 

1. Add the executable name to existing client/new messages, changing the number of parameters. I do not want that, at all, because it breaks compatibility. But I want to publically write that down :)



P.S. 
Programs that have icon names that are completely different from their executable name will never have icons in the GUI.  This is just an educated guess though. And maybe that never happens, because XDG standard or so.  If this can indeed happen we should just accept that as a fact. Adding  "icon-path" or "my desktop file" to the clients announce message is out of the question.

**Comment by diovudau** [comment]
Fixed with obvious solution 1).  
This works flawlessly with legacy-gui and even NTK non-session-manager, if you want. 

Sorry, that was a lot of text for 4 lines of code change, but I needed that for the decision-making process.
