### ISSUE TITLE
Missing manpages for packaging in Fedora and Debian/Ubuntu.

### ISSUE THREAD

**Issue by eeickmeyer** [linuxaudio/new-session-manager#42]
Hi there! Per Debian packaging policy and Fedora packaging guidelines, any files installed to /usr/bin should also include a manpage. While these aren't blockers since you have existing documentation, it would be advisable to create proper manpages.

Thanks!

**Comment by diovudau** [comment]
Some of the installed executables are not meant to be executed, one is even just a symlink. 
What is the best practice? Provide a unique manpage for each and every tool, even if it is only one sentence?
Provide a manpage for the package and symlink all others to it? 

@dvzrv  How about Arch?

**Comment by falkTX** [comment]
I think the best practice is to include a manpage for each binary, ignoring symlinks.
The manpage just has a description of the tool and the available CLI options and environment variables.

**Comment by diovudau** [comment]
There are now manpages for all our files in /usr/bin.
