### ISSUE TITLE
[Dev-Log] API Version vs. Server/Client capabilities

### ISSUE THREAD

**Issue by diovudau** [linuxaudio/new-session-manager#44]
> This is not a bug report but a public "dev-log" with the option for anyone to comment. 

The NSM API was always versioned. Now with our fork there is some progress which requires incrementing the minor version. 
See also our own API document:

https://linuxaudio.github.io/new-session-manager/api/index.html#_api_versions_and_behaviour_changes

While fixing the code and adapting the API document over the last weeks I realized that there may be redundancy, or overlapping responsibilities, when it comes to API versions and so-called capabilities, which are tokens send while clients and server handshake to negotiate features.

_Why announce (server) capabilities if there is already an API version?_

For the client capabilities side there is no issue. Some features are just client-optional, like hiding/showing the GUI or the client sending progress-in-percent to the server. 

But shouldn't the server always support all features described in the API anyway?

1. The existinence of capabilities might imply that different server implementations with only subsets of features were a design-consideration by the original author from the start. The Non-SM manuals, website and API also indicate this. However, given how very negative the original authors reactions were concerning such server-implementations (RaySession, Carla, this fork) one can only deduce that this was not the case.

1. The client has no way of knowing the server API version.  It is not announced over OSC ( I might add this before the next release). Server capabilities might have been intended to be the version check, but indirectly. If that is the case it would make the API version not needed, except for documentation reasons.

1. There is no plan to change the current scheme. The capabilities will stay in and the API-versioning will be taken seriously. Starting from this as a baseline my own brainstorming can see some usecases. For example: The server `nsmd` might get a command line switch that will remove `:optional-gui:` from the announced server-capabilities. This will create a mode where every client is always visible.  

Maybe some of you have more ideas why having both, API Versions and Capabilities, is good to have. Maybe some of you have good reasons to deprecate one or the other, before too much development goes into that in the future?

**Comment by falkTX** [comment]
Speaking from experience, using version numbers as a way to identify features is asking for trouble.
The server capabilities is a nice way to know what it supports, in a way that is forwards compatible with any new stuff we might add to it. Sure we could compare versions, but the original NSM can bump its version at any time with incompatible news features. (e.g. 1.5 of Non-SM adds ":shit-talk:" while 1.5 of New-SM has ":community:", ":packaged-in-ubuntu:" etc etc; even though both are at the same version, they do not support the same thing)

It is intentional that clients don't know what version the server runs, and they do not have to care.
We just need to ensure that every single feature reported by the server is implemented according to well-defined specs.

**Comment by diovudau** [comment]
Explicit is better than implicit. As long as we are carefull and don't exceed the max length of the OSC capabilties message.

Capabilities are all Server/GUI/Clients will need to care about when it comes to MINOR and PATCH-level.  So be it.

The API document and versioning will still be used and written with care. It is the source of a complete implementation, and by that a design document for our existing `nsmd`.

Let this be a reference for future feature requests as well:  For aboive reasons there will be no  `/nsm/server/version` and `/nsm/server/api_version` messages, because it is anticipated that they will be used to check for features, which we anticipate to fail.

This "issue" will be closed after the next release.
