### ISSUE TITLE
Legacy-GUI: buttons get squeezed when shrinken in size

### ISSUE THREAD

**Issue by theGreatWhiteShark** [linuxaudio/new-session-manager#58]
When shrinking the window of the legacy GUI to a size not sufficient for the stop and save buttons to be fully displayed they get squeezed quite a lot. (Observed in i3 4.17.1)

![squeezed_buttons](https://user-images.githubusercontent.com/14164547/96244894-fab3b080-0fa6-11eb-9cea-0259c1ca4907.png)

**Comment by falkTX** [comment]
There should be a minimal window size, set as the size to fit all the main-action buttons in the top.
Going below that size is unsupported.

Or alternatively, patches welcome to make it more responsive :)

You can also consider using https://www.laborejo.org/agordejo/ instead of the legacy gui

**Comment by theGreatWhiteShark** [comment]
> patches welcome to make it more responsive :)

Awesome. I already thought about fixing these minor UI shortcomings in Non-Session-Manager but did shy away from reading into FLTK considering the acceptance rate of bug fixes and other contributions back then. It might take a couple of months till I find some spare time but I will give it a shot.

**Comment by falkTX** [comment]
> but did shy away from reading into FLTK considering the acceptance rate of bug fixes and other contributions back then.

You are likely thinking of some other "non" project ;)

**Comment by theGreatWhiteShark** [comment]
Indeed ;)
