### ISSUE TITLE
Amsynth NSM implementation not according to the API

### ISSUE THREAD

**Issue by grammoboy2** [linuxaudio/new-session-manager#60]
Fyi
https://github.com/amsynth/amsynth/issues/184

**Comment by falkTX** [comment]
Thanks, but please provide a better ticket title next time

**Comment by falkTX** [comment]
Also, not sure how useful it is to report issues against NSM project of clients that do not have good implementations...

@diovudau thoughts?

**Comment by diovudau** [comment]
We will keep this around as a reminder until resolved and also as a sign that we, upstream, are here to contact and get help.
It is of course true that application-specific problems should be in their issue tracker, thus I think this reference is tolerable.

**Comment by grammoboy2** [comment]
Somehow you want to have a central place where people who use NSM, know which apps have bugs and which not I think. The chain is as strong as the weakest link. NSM only works if the system of parts work.

It might be possible to open a special github repo where people can link to if they open a NSM related bug for a application on github.

Ideally you would have a Debian/Ubuntu repository like Kxstudio has for plugins, but then for NSM applications. Not saying that Kxstudio should do also NSM, but if someone would do it like that for NSM, that might improve the situation quite a bit.

Just some ideas.

**Comment by diovudau** [comment]
amsynth issue is handled upstream now.
