### ISSUE TITLE
List of apps with NSM support (and bugs)

### ISSUE THREAD

**Issue by grammoboy2** [linuxaudio/new-session-manager#62]
FYI, I made a list of supported apps with NSM support months ago. Not too much new info, but it points to a bug in Luppp for instance. Do with it what you like.

30-01-2020
List of apps with nsm support:

non-timeline
non-mixer
non-sequencer

jackpatch
nsm-proxy
non-midi-mapper

zynaddsubfx
petri-foo
ardour
mfp
carla
qtractor
synthV1_jack
samplV1_jack
drumkV1_jack
qmidiarp
synthpod_jack
hydrogen (basis support, not working here)
patroneo - Easy Pattern Sequencer
fluajho - SF2 Sample Player
vico - midi sequencer (application had a vital bug here)
laborejo - music composing tool and notation editor (application in heavy development at the moment)
adljack OPL3/OPN2 synthesizer
Shuriken Beat Slicer
amsynth Analog Modelling Synthesizer
luppp (!)
Loopp (fork of Luppp) (!)
pynsm2 includes a pyQt example client
ams AlsaModularSynth  (Lastest Ubuntu/ Debian Testing)
radium_compressor (https://github.com/kmatheussen/radium_compressor)

NSM patches:

Yoshimi Patch
ZynAddSubFX Patch (no longer necessary)
Azr3-JACK Patch
Zita-rev1 Git Repo
Zita-at1 Git Repo
AlsaModularSynth Git Repo (package is in later versions of Debian/Ubuntu)

! Luppp has a nsm related bug: https://github.com/openAVproductions/openAV-Luppp/issues/301

More info: http://non.tuxfamily.org/wiki/ApplicationsSupportingNsm

**Comment by diovudau** [comment]
Thank you for your contribution. I will review the list and merge it into this githubs wiki for New-SM.

**Comment by grammoboy2** [comment]
Petri-Foo doesn't compile
https://github.com/petri-foo/Petri-Foo/issues/41

Nor it's fork
https://github.com/sollapse/Petri-Foo/commit/3f2a456d95b775d4bc855806c73029c55120b705

**Comment by abrolag** [comment]
Yoshimi patch was written against an extremely old version of Yoshimi and can no longer be applied.
Nobody here has the time to produce an upgrade, but if anyone else wants to we'd be quite happy to look at it.

**Comment by diovudau** [comment]
I'll close this because all relevant information is (now) in our github wiki.  
For the Yoshimi patch I can only hope to remember that if someone offers to help someday.
