### ISSUE TITLE
NSM wishlist

### ISSUE THREAD

**Issue by grammoboy2** [linuxaudio/new-session-manager#63]
Months ago I made a 'wishlist' and contacted software developers to support NSM. List is here. Do with it what you like:

Wishlist for applications that 'should' have nsm support:

1) Carla-single
2) Vcvrack
3) seq66 (seq24)
4) Aeolus
5) Ingen
6) Muse3
7) Rakarrack
8) Guitarix (done)
9) jalv
10) sooperlooper
11) kluppe

 Radium tracker (done)

Musician X  wishlist:
1. Rakarrack
2. kluppe (Louigi is probably the only.. but important user)
3. Hydrogen
4. seq24

Active, will add nsm support:
Radium (already done)

Muse (Will add it, date not known. Accepts donation for it to speed things up)
https://github.com/muse-sequencer/muse/issues/657

Carla-single (will add it for Carla version 3.0?)

Sequencer64  (Will add it within the coming months)

Active, open for it:

Guitarix (recently implemented)

Hydrogen (has basic nsm support, actively work in progress)
https://github.com/hydrogen-music/hydrogen/pull/792

Yoshimi, there is a patch for it, but has never been added to Yoshimi. 
http://non.tuxfamily.org/wiki/NsmPatches

Giada (wants it, but needs help with it)

Active, but no priority yet:
Harmonyseq (want clean up his stuff first)
Jalv (open to accept a patch)

Active, unknown:

Vcvrack (interesting eurorack softsynth, but hard to implement?)

Not active anymore afaik:

AZR3-jack organ. There is a patch for it, don't think this is added to the source yet
http://non.tuxfamily.org/wiki/NsmPatches

Rakarrack 
Sooperlooper 
Kluppe

Seq24 (now active as sequencer64)
Phasex (has jack-session support, app is not stable enough)

**Comment by falkTX** [comment]
Did you just copy&paste dump your internal notes?

This info is better placed in a wiki, not as a ticket, so others can edit.
Thanks, though not sure how much or if we can do anything about those at all.

**Comment by diovudau** [comment]
We will keep this list around as a reminder, until there is a better place for it.
At the moment it is more important to keep all information and questions in one place than spread it out over a secondary note taking tool that is rarely used.

**Comment by grammoboy2** [comment]
Today I would put aeolus and Ingen high on the list, so updated.
Like I said feel free to do what you want with it. But I thought it could be useful to share.

**Comment by diovudau** [comment]
Everything here has been transferred to the relevant places or is handled in another projects issue tracker.
