### ISSUE TITLE
setting default session folder at initial startup

### ISSUE THREAD

**Issue by theGreatWhiteShark** [linuxaudio/new-session-manager#70]
I want to propose a compromise regarding the default session folder in the `nsm-legacy-gui`. But first, the

### problem

- the former `~/NSM Sessions` folder is created by default and litters the home folder + there is a white space inside
- the new default folder `~/.local/share/nsm` is quite obscure. I would not feel comfortable suggesting the application to non-technical linux users anymore. Because - while there is a dedicated command line argument - there is no way for setting the default session folder from the GUI and all files end up deep down in a hidden folder

### proposal

`nsm-legacy-gui` could store/read its default session directory to/from an XDG-compatible location. If this one does not exist (at the initial startup), there could be a dialog telling the user to choose a default folder. Ideally, this could be a window allowing the user to browser through the file tree and select a directory by mouse (if this is supported in FLTK without us reinventing the wheel). Alternative, a simple line edit querying for a path relative to the home folder with a decent default should also do.

**Comment by diovudau** [comment]
Your contributions and suggestions are most welcome. But please let's keep that in the issue where that belongs: #15 
We can answer there with inline-quotes of this, no need to repost. 
I'm closing and locking this purely for formal issue-management reasons.
