### ISSUE TITLE
Copy documentation to this repository

### ISSUE THREAD

**Issue by diovudau** [linuxaudio/new-session-manager#9]
The original NSM docs are Creative Commons licensed.  We should copy their content here.

**Comment by trebmuh** [comment]
I can probably help with that.

**Comment by diovudau** [comment]
I am currently transfering the API docs myself, because I want to make absolutely sure licensing is done correctly and all changes are transparent. This is the only part we copy from NON-SM. 

If not strictly needed we will not adapt the Non-Session-Manager/Legacy-GUI manual but link to the existing [NON-SM manual](http://non.tuxfamily.org/session-manager/doc/MANUAL.html).

What we need however is extended documentation, or rather tutorials, that 

- Show program developers how to integrate nsm-support in their existing software 
  -  in C / C++ (nsm.h)
  - in Python (pynsmclient2)
- Show 3rd party programmers how to patch inactive or abandoned software with nsm-support
- List best practices for new software to avoid redundancy and complexity
  - for example in which order to open clients, jack etc.
  - how to implement save, export etc.
  - possibly (my personal choice) how to build an exclusive nsm-client first and then implement a local pseudo-server to make the software standalone
- Actual user manuals (click this, type that) and guides of what is possible, what to expect and where the limits of session management, as well as frequent questions and common misconceptions (this overlaps with a Argodejo documentation)
- "Cool Stuff" like running nsm headless, connecting over network, integrating a setup into your OS for improved convenience, case studies of complete audio production systems and workflows.

**Comment by brummer10** [comment]
I would prefer when you use a extra repository for the manual. It will keep the download size for the daemon itself small. 
You could setup a github.io page on the external repository and link it to the readme here, for example.

**Comment by diovudau** [comment]
The manual will be in the same repository.  
Note that the manual is not extensive image galleries or video tutorials. These would be outside of this repository. I am talking about the core text documentation.

**Comment by brummer10** [comment]
Ah, I had the impression you talk about the html pages.

**Comment by diovudau** [comment]
I do, the API specs are presented as HTML. I want them close to the code files. But we are talking about kilobytes here. No images.

**Comment by brummer10** [comment]
Okay, I don't like this. ¯\_(⊙︿⊙)_/¯

**Comment by diovudau** [comment]
Done.   https://linuxaudio.github.io/new-session-manager/api/index.html
Except the layout this is an exact copy, to have a known state at the beginning and we can modify from here in a traceable manner.

**Comment by brummer10** [comment]
I voted for a extra repository for documentation, as it is not unlikely that it get extended. For example, real world example client implementation, a C++ wrapper, etc. 
Maybe a API documentation with doxygen and graphviz, . . which could easily blow up the size.
